STATUS_HWERROR=5
STATUS_SYSRQ=6
# panic type
PANIC_UAF=1
PANIC_DOUBLEFREE=2
PANIC_OOBREAD=3
PANIC_OOBWRITE=4
PANIC_NULLPOINTER=5
PANIC_UNINITVAR=6
PANIC_STACKCORRUPTION=7
PANIC_INVALIDIPPTR=8
PANIC_INVALIDDATAPTR=9
PANIC_BUGON=10
PANIC_DIVIDEERROR=11
PANIC_HARDLOCKUP=12
PANIC_SOFTLOCKUP=13
PANIC_HUNGTASK=14
PANIC_RCUSTALL=15

