WORK_PATH=`dirname $0`

trace_sig_enable() {
	echo "enable" > /proc/sysak_sig_trace
}

trace_sig_disable() {
	echo "disable" > /proc/sysak_sig_trace
}

usage() {
	echo "$0 [opt] -e|d"
	echo "   -e, enable"
	echo "   -d, disable"
	echo "opt:"
	echo "   -p, pid"
	echo "   -c, comm"
	echo "   -s, signal"
}

while getopts 'p:c:s:edrh' OPT; do
	case $OPT in
		"h")
			usage
			exit 0
			;;
		"p")
			echo "pid $OPTARG" > /proc/sysak_sig_trace
			;;
		"c")
			echo "comm $OPTARG" > /proc/sysak_sig_trace
			;;
		"s")
			echo "sig $OPTARG" > /proc/sysak_sig_trace
			;;
		"e")
			trace_enable=true
			;;
		"d")
			trace_disable=true;
			;;
		"r")
			dmesg | grep "generated by:" 
			;;
		*)
			usage
			exit -1
		;;
	esac
done


if [ $trace_enable ]; then
	trace_sig_enable
fi

if [ $trace_disable ]; then
	trace_sig_disable
fi
